name: Checkout

on: workflow_dispatch

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Before Checkout
        run: |
          pwd
          ls -la

      - name: Checkout
        uses: actions/checkout@v4

      - name: After Checkout
        run: |
          pwd
          ls -la